# Generated by Django 4.2.4 on 2024-01-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='actions',
            field=models.IntegerField(default=0),
        ),
    ]
